service: school-management-system

frameworkVersion: '3'

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript
provider:
  name: aws
  timeout: 30
  runtime: nodejs16.x
  region: eu-north-1
  environment:
    DYNAMODB_TABLE: shoolTable
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  getSchool:
    handler: src/api/getSchoolApi.handler
    events:
      - http:
          path: school/{id}
          method: get
  postSchool:
    handler: src/api/postSchoolApi.handler
    events:
      - http:
          path: school
          method: post
  deleteSchool:
    handler: src/api/deleteSchoolApi.handler
    events:
      - http:
          path: school/{id}
          method: delete
  patchSchool:
    handler: src/api/patchSchoolApi.handler
    events:
      - http:
          path: school/{id}
          method: patch
  getStudent:
    handler: src/api/getStudentApi.handler
    events:
      - http:
          path: student/{id}
          method: get
  postStudent:
    handler: src/api/postStudentApi.handler
    events:
      - http:
          path: student
          method: post
  deleteStudent:
    handler: src/api/deleteStudentApi.handler
    events:
      - http:
          path: student/{id}
          method: delete
  patchStudent:
    handler: src/api/patchStudentApi.handler
    events:
      - http:
          path: student/{id}
          method: patch

custom:
  stage: dev
  dynamodb:
    seed:
      domain:
        sources:
          - table: schoolTable
          - sources: [./resources/migrations/v0.json]
    stages:
      - dev
    start:
      port: 41581
      inMemory: true
      migrate: true
      sharedDb: true
  

resources:
  Resources:
    SchoolTable:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: schoolTable
    StudentTable:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: studentTable

