service: school-management
frameworkVersion: '2 || 3'

custom:
  tableName: 'SchoolTable'
provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [DynamoData.Resources.TokensTable, Arn]
  environment:
    SCHOOL_TABLE: SchoolTable

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

functions:
  getSchool:
    handler: src/api/getSchoolApi.handler
    events:
      - http:
          path: school/{id}
          method: get
  postSchool:
    handler: src/api/postSchoolApi.handler
    events:
      - http:
          path: school
          method: post
  deleteSchool:
    handler: src/api/deleteSchoolApi.handler
    events:
      - http:
          path: school/{id}
          method: delete
  patchSchool:
    handler: src/api/patchSchoolApi.handler
    events:
      - http:
          path: school/{id}
          method: patch

resources:
  Resources:
    SchoolTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}